services:
  gps-spoofer:
    image: akudamatata/ios-location-spoofer-web:latest
    container_name: gps-spoofer
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - PORT=8080
      - TOKEN=${TOKEN}
      - AMAP_KEY=${AMAP_KEY}
      - DATA_DIR=/data
